import { Job, Applicant } from './types';

export const DUMMY_JOBS: Job[] = [
  {
    id: '1',
    tenderName: 'Sai Caterers',
    tenderRating: 4.8,
    isVerified: true,
    type: 'Catering',
    subType: 'Bokeh Serving',
    date: 'Sun, 11 May',
    time: '6 PM–11 PM',
    location: 'Indiranagar',
    distance: '4.5 km',
    transport: '🚇 Metro: Indiranagar Stn (800m walk)',
    pay: '₹180/hour',
    payType: 'hourly',
    food: 'Provided (Veg)',
    travel: '₹120',
    foodType: 'Non-Veg',
    spotsTotal: 4,
    spotsFilled: 2,
    status: 'active'
  },
  {
    id: '2',
    tenderName: 'QuickShift Movers',
    tenderRating: 4.5,
    isVerified: true,
    type: 'Home Shifting',
    subType: 'Packing',
    date: 'Mon, 12 May',
    time: '8 AM–2 PM',
    location: 'Whitefield',
    distance: '12.8 km',
    transport: '🚌 Bus 335E from Majestic (50 min)',
    pay: '₹1200/job',
    payType: 'fixed',
    food: 'Not provided',
    travel: '₹200',
    foodType: 'N/A',
    spotsTotal: 3,
    spotsFilled: 1,
    status: 'applied'
  },
  {
    id: '3',
    tenderName: 'Annapurna Events',
    tenderRating: 4.9,
    isVerified: true,
    type: 'Catering',
    subType: 'Manual Serving',
    date: 'Sat, 10 May',
    time: '11 AM–5 PM',
    location: 'HSR Layout',
    distance: '2.1 km',
    transport: '🛺 Auto ~₹60',
    pay: '₹150/hour',
    payType: 'hourly',
    food: 'Provided (Both)',
    travel: 'Not included',
    foodType: 'Veg',
    spotsTotal: 8,
    spotsFilled: 5,
    status: 'active'
  },
  {
    id: '4',
    tenderName: 'MoveSmart Logistics',
    tenderRating: 4.3,
    isVerified: false,
    type: 'Home Shifting',
    subType: 'Moving',
    date: 'Wed, 14 May',
    time: '9 AM–3 PM',
    location: 'Jayanagar',
    distance: '6.7 km',
    transport: '🚌 Bus 201 from Koramangala (25 min)',
    pay: '₹1500/job',
    payType: 'fixed',
    food: 'Provided (Veg)',
    travel: '₹150',
    foodType: 'N/A',
    spotsTotal: 2,
    spotsFilled: 2,
    status: 'full'
  },
  {
    id: '5',
    tenderName: 'Royal Feast Catering',
    tenderRating: 4.6,
    isVerified: true,
    type: 'Catering',
    subType: 'Bokeh Serving',
    date: 'Fri, 16 May',
    time: '5 PM–10 PM',
    location: 'Koramangala',
    distance: '1.5 km',
    transport: '🚶 Walkable (15 min)',
    pay: '₹200/hour',
    payType: 'hourly',
    food: 'Provided (Non-Veg)',
    travel: 'Not included',
    foodType: 'Non-Veg',
    spotsTotal: 6,
    spotsFilled: 4,
    status: 'active'
  }
];

export const DUMMY_APPLICANTS: Applicant[] = [
  {
    id: 'a1',
    name: 'Rahul Sharma',
    rating: 4.8,
    jobsCompleted: 23,
    isVerified: true,
    skills: ['Bokeh Serving', 'Setup'],
    availability: 'available',
    foodComfort: true,
    photo: 'https://i.pravatar.cc/150?u=a1'
  },
  {
    id: 'a2',
    name: 'Priya Nair',
    rating: 4.6,
    jobsCompleted: 15,
    isVerified: true,
    skills: ['Manual Serving', 'Bokeh Serving'],
    availability: 'available',
    foodComfort: true,
    photo: 'https://i.pravatar.cc/150?u=a2'
  },
  {
    id: 'a3',
    name: 'Karthik Gowda',
    rating: 4.4,
    jobsCompleted: 8,
    isVerified: false,
    skills: ['Bokeh Serving'],
    availability: 'assigned',
    foodComfort: true,
    photo: 'https://i.pravatar.cc/150?u=a3'
  },
  {
    id: 'a4',
    name: 'Meena Raj',
    rating: 4.9,
    jobsCompleted: 31,
    isVerified: true,
    skills: ['Bokeh Serving', 'Kitchen Helper'],
    availability: 'available',
    foodComfort: true,
    photo: 'https://i.pravatar.cc/150?u=a4'
  },
  {
    id: 'a5',
    name: 'Arjun Desai',
    rating: 4.2,
    jobsCompleted: 5,
    isVerified: false,
    skills: ['Manual Serving'],
    availability: 'unavailable',
    foodComfort: false,
    photo: 'https://i.pravatar.cc/150?u=a5'
  }
];
